// Map of country name to nationality
export interface Nationality {
  country: string; // The country name from country-codes.ts
  nationality: string; // The nationality form (e.g., "Ghanaian" for "Ghana")
}

export const nationalityMap: Record<string, string> = {
  "ANYWHERE": "Global",
  "Ghana": "Ghanaian",
  "United States": "American",
  "United Kingdom": "British",
  "Canada": "Canadian",
  "Nigeria": "Nigerian",
  "South Africa": "South African",
  "Afghanistan": "Afghan",
  "Albania": "Albanian",
  "Algeria": "Algerian",
  "American Samoa": "American Samoan",
  "Andorra": "Andorran",
  "Angola": "Angolan",
  "Anguilla": "Anguillan",
  "Antarctica": "Antarctic",
  "Antigua and Barbuda": "Antiguan, Barbudan",
  "Argentina": "Argentine",
  "Armenia": "Armenian",
  "Aruba": "Aruban",
  "Australia": "Australian",
  "Austria": "Austrian",
  "Azerbaijan": "Azerbaijani",
  "Bahamas": "Bahamian",
  "Bahrain": "Bahraini",
  "Bangladesh": "Bangladeshi",
  "Barbados": "Barbadian",
  "Belarus": "Belarusian",
  "Belgium": "Belgian",
  "Belize": "Belizean",
  "Benin": "Beninese",
  "Bermuda": "Bermudian",
  "Bhutan": "Bhutanese",
  "Bolivia": "Bolivian",
  "Bosnia and Herzegovina": "Bosnian, Herzegovinian",
  "Botswana": "Motswana, Batswana",
  "Brazil": "Brazilian",
  "British Indian Ocean Territory": "British",
  "Brunei Darussalam": "Bruneian",
  "Bulgaria": "Bulgarian",
  "Burkina Faso": "Burkinabé",
  "Burundi": "Burundian",
  "Cambodia": "Cambodian",
  "Cameroon": "Cameroonian",
  "Cape Verde": "Cape Verdean",
  "Cayman Islands": "Caymanian",
  "Central African Republic": "Central African",
  "Chad": "Chadian",
  "Chile": "Chilean",
  "China": "Chinese",
  "Christmas Island": "Christmas Islander",
  "Cocos (Keeling) Islands": "Cocos Islander",
  "Colombia": "Colombian",
  "Comoros": "Comorian",
  "Congo": "Congolese",
  "Congo, DR": "Congolese",
  "Cook Islands": "Cook Islander",
  "Costa Rica": "Costa Rican",
  "Cote d'Ivoire": "Ivorian",
  "Croatia": "Croatian",
  "Cuba": "Cuban",
  "Cyprus": "Cypriot",
  "Czech Republic": "Czech",
  "Denmark": "Danish",
  "Djibouti": "Djiboutian",
  "Dominica": "Dominican",
  "Dominican Republic": "Dominican",
  "Ecuador": "Ecuadorian",
  "Egypt": "Egyptian",
  "El Salvador": "Salvadoran",
  "Equatorial Guinea": "Equatorial Guinean",
  "Eritrea": "Eritrean",
  "Estonia": "Estonian",
  "Ethiopia": "Ethiopian",
  "Falkland Islands": "Falkland Islander",
  "Faroe Islands": "Faroese",
  "Fiji": "Fijian",
  "Finland": "Finnish",
  "France": "French",
  "French Guiana": "French Guianese",
  "French Polynesia": "French Polynesian",
  "Gabon": "Gabonese",
  "Gambia": "Gambian",
  "Georgia": "Georgian",
  "Germany": "German",
  "Gibraltar": "Gibraltarian",
  "Greece": "Greek",
  "Greenland": "Greenlandic",
  "Grenada": "Grenadian",
  "Guadeloupe": "Guadeloupean",
  "Guam": "Guamanian",
  "Guatemala": "Guatemalan",
  "Guinea": "Guinean",
  "Guinea-Bissau": "Guinea-Bissauan",
  "Guyana": "Guyanese",
  "Haiti": "Haitian",
  "Holy See (Vatican City)": "Vatican",
  "Honduras": "Honduran",
  "Hong Kong": "Hong Konger",
  "Hungary": "Hungarian",
  "Iceland": "Icelandic",
  "India": "Indian",
  "Indonesia": "Indonesian",
  "Iran": "Iranian",
  "Iraq": "Iraqi",
  "Ireland": "Irish",
  "Israel": "Israeli",
  "Italy": "Italian",
  "Jamaica": "Jamaican",
  "Japan": "Japanese",
  "Jordan": "Jordanian",
  "Kazakhstan": "Kazakhstani",
  "Kenya": "Kenyan",
  "Kiribati": "I-Kiribati",
  "North Korea": "North Korean",
  "South Korea": "South Korean",
  "Kuwait": "Kuwaiti",
  "Kyrgyzstan": "Kyrgyzstani",
  "Laos": "Lao",
  "Latvia": "Latvian",
  "Lebanon": "Lebanese",
  "Lesotho": "Mosotho",
  "Liberia": "Liberian",
  "Libya": "Libyan",
  "Liechtenstein": "Liechtensteiner",
  "Lithuania": "Lithuanian",
  "Luxembourg": "Luxembourger",
  "Macao": "Macanese",
  "North Macedonia": "Macedonian",
  "Madagascar": "Malagasy",
  "Malawi": "Malawian",
  "Malaysia": "Malaysian",
  "Maldives": "Maldivian",
  "Mali": "Malian",
  "Malta": "Maltese",
  "Marshall Islands": "Marshallese",
  "Martinique": "Martinican",
  "Mauritania": "Mauritanian",
  "Mauritius": "Mauritian",
  "Mayotte": "Mahoran",
  "Mexico": "Mexican",
  "Micronesia": "Micronesian",
  "Moldova": "Moldovan",
  "Monaco": "Monégasque",
  "Mongolia": "Mongolian",
  "Montenegro": "Montenegrin",
  "Montserrat": "Montserratian",
  "Morocco": "Moroccan",
  "Mozambique": "Mozambican",
  "Myanmar": "Burmese",
  "Namibia": "Namibian",
  "Nauru": "Nauruan",
  "Nepal": "Nepali",
  "Netherlands": "Dutch",
  "New Caledonia": "New Caledonian",
  "New Zealand": "New Zealander",
  "Nicaragua": "Nicaraguan",
  "Niger": "Nigerien",
  "Niue": "Niuean",
  "Norfolk Island": "Norfolk Islander",
  "Northern Mariana Islands": "Northern Mariana Islander",
  "Norway": "Norwegian",
  "Oman": "Omani",
  "Pakistan": "Pakistani",
  "Palau": "Palauan",
  "Palestine": "Palestinian",
  "Panama": "Panamanian",
  "Papua New Guinea": "Papua New Guinean",
  "Paraguay": "Paraguayan",
  "Peru": "Peruvian",
  "Philippines": "Filipino",
  "Pitcairn": "Pitcairn Islander",
  "Poland": "Polish",
  "Portugal": "Portuguese",
  "Puerto Rico": "Puerto Rican",
  "Qatar": "Qatari",
  "Reunion": "Réunionese",
  "Romania": "Romanian",
  "Russia": "Russian",
  "Rwanda": "Rwandan",
  "Saint Barthélemy": "Saint Barthélemy Islander",
  "Saint Helena": "Saint Helenian",
  "Saint Kitts and Nevis": "Kittitian, Nevisian",
  "Saint Lucia": "Saint Lucian",
  "Saint Martin": "Saint Martin Islander",
  "Saint Pierre and Miquelon": "Saint Pierre and Miquelon Islander",
  "Saint Vincent and the Grenadines": "Saint Vincentian",
  "Samoa": "Samoan",
  "San Marino": "Sammarinese",
  "Sao Tome and Principe": "São Toméan",
  "Saudi Arabia": "Saudi Arabian",
  "Senegal": "Senegalese",
  "Serbia": "Serbian",
  "Seychelles": "Seychellois",
  "Sierra Leone": "Sierra Leonean",
  "Singapore": "Singaporean",
  "Sint Maarten": "Sint Maartener",
  "Slovakia": "Slovak",
  "Slovenia": "Slovenian",
  "Solomon Islands": "Solomon Islander",
  "Somalia": "Somali",
  "Spain": "Spanish",
  "Sri Lanka": "Sri Lankan",
  "Sudan": "Sudanese",
  "Suriname": "Surinamese",
  "Svalbard and Jan Mayen": "Svalbard and Jan Mayen Islander",
  "Swaziland": "Swazi",
  "Sweden": "Swedish",
  "Switzerland": "Swiss",
  "Syria": "Syrian",
  "Taiwan": "Taiwanese",
  "Tajikistan": "Tajikistani",
  "Tanzania": "Tanzanian",
  "Thailand": "Thai",
  "Timor-Leste": "Timorese",
  "Togo": "Togolese",
  "Tokelau": "Tokelauan",
  "Tonga": "Tongan",
  "Trinidad and Tobago": "Trinidadian, Tobagonian",
  "Tunisia": "Tunisian",
  "Turkey": "Turkish",
  "Turkmenistan": "Turkmen",
  "Turks and Caicos Islands": "Turks and Caicos Islander",
  "Tuvalu": "Tuvaluan",
  "Uganda": "Ugandan",
  "Ukraine": "Ukrainian",
  "United Arab Emirates": "Emirati",
  "Uruguay": "Uruguayan",
  "Uzbekistan": "Uzbekistani",
  "Vanuatu": "Ni-Vanuatu",
  "Venezuela": "Venezuelan",
  "Vietnam": "Vietnamese",
  "Virgin Islands, British": "British Virgin Islander",
  "Virgin Islands, U.S.": "U.S. Virgin Islander",
  "Wallis and Futuna": "Wallisian, Futunan",
  "Western Sahara": "Sahrawi",
  "Yemen": "Yemeni",
  "Zambia": "Zambian",
  "Zimbabwe": "Zimbabwean"
};

// Function to convert country name to nationality
export function getCountryNationality(countryName: string): string {
  return nationalityMap[countryName] || countryName;
}