import { City } from "./cities";

// This file contains an extensive list of U.S. cities and towns
// Organized by state for better management

// Helper function to create city objects for US cities
const usCity = (city: string, state: string): City => ({
  city: `${city}`,
  country: "United States"
});

// Export cities by state for better organization
export const alabamaCities: City[] = [
  usCity("Birmingham", "Alabama"),
  usCity("Montgomery", "Alabama"),
  usCity("Mobile", "Alabama"),
  usCity("Huntsville", "Alabama"),
  usCity("Tuscaloosa", "Alabama"),
  usCity("Hoover", "Alabama"),
  usCity("Dothan", "Alabama"),
  usCity("Auburn", "Alabama"),
  usCity("Decatur", "Alabama"),
  usCity("Madison", "Alabama"),
  usCity("Florence", "Alabama"),
  usCity("Gadsden", "Alabama"),
  usCity("Vestavia Hills", "Alabama"),
  usCity("Phenix City", "Alabama"),
  usCity("Prattville", "Alabama"),
  usCity("Alabaster", "Alabama"),
  usCity("Bessemer", "Alabama"),
  usCity("Enterprise", "Alabama"),
  usCity("Opelika", "Alabama"),
  usCity("Homewood", "Alabama"),
  usCity("Athens", "Alabama"),
  usCity("Anniston", "Alabama"),
  usCity("Northport", "Alabama"),
  usCity("Pelham", "Alabama"),
  usCity("Mountain Brook", "Alabama"),
  usCity("Oxford", "Alabama"),
  usCity("Albertville", "Alabama"),
  usCity("Selma", "Alabama"),
  usCity("Trussville", "Alabama"),
  usCity("Fairhope", "Alabama"),
  usCity("Talladega", "Alabama"),
  usCity("Helena", "Alabama"),
  usCity("Center Point", "Alabama"),
  usCity("Troy", "Alabama"),
  usCity("Cullman", "Alabama"),
  usCity("Scottsboro", "Alabama"),
  usCity("Millbrook", "Alabama"),
  usCity("Foley", "Alabama"),
  usCity("Jasper", "Alabama"),
  usCity("Hartselle", "Alabama"),
  usCity("Fort Payne", "Alabama"),
  usCity("Gardendale", "Alabama"),
  usCity("Muscle Shoals", "Alabama"),
  usCity("Saraland", "Alabama"),
  usCity("Sylacauga", "Alabama"),
  usCity("Pell City", "Alabama"),
  usCity("Calera", "Alabama"),
  usCity("Fairfield", "Alabama"),
  usCity("Jacksonville", "Alabama"),
  usCity("Gulf Shores", "Alabama"),
];

export const alaskaCities: City[] = [
  usCity("Anchorage", "Alaska"),
  usCity("Fairbanks", "Alaska"),
  usCity("Juneau", "Alaska"),
  usCity("Wasilla", "Alaska"),
  usCity("Sitka", "Alaska"),
  usCity("Ketchikan", "Alaska"),
  usCity("Kenai", "Alaska"),
  usCity("Kodiak", "Alaska"),
  usCity("Bethel", "Alaska"),
  usCity("Palmer", "Alaska"),
  usCity("Homer", "Alaska"),
  usCity("Unalaska", "Alaska"),
  usCity("Barrow", "Alaska"),
  usCity("Soldotna", "Alaska"),
  usCity("Valdez", "Alaska"),
  usCity("Nome", "Alaska"),
  usCity("Kotzebue", "Alaska"),
  usCity("Seward", "Alaska"),
  usCity("Wrangell", "Alaska"),
  usCity("Dillingham", "Alaska"),
  usCity("Cordova", "Alaska"),
  usCity("North Pole", "Alaska"),
  usCity("Houston", "Alaska"),
  usCity("Craig", "Alaska"),
  usCity("Hooper Bay", "Alaska"),
];

export const arizonaCities: City[] = [
  usCity("Phoenix", "Arizona"),
  usCity("Tucson", "Arizona"),
  usCity("Mesa", "Arizona"),
  usCity("Chandler", "Arizona"),
  usCity("Scottsdale", "Arizona"),
  usCity("Glendale", "Arizona"),
  usCity("Gilbert", "Arizona"),
  usCity("Tempe", "Arizona"),
  usCity("Peoria", "Arizona"),
  usCity("Surprise", "Arizona"),
  usCity("Yuma", "Arizona"),
  usCity("Avondale", "Arizona"),
  usCity("Goodyear", "Arizona"),
  usCity("Flagstaff", "Arizona"),
  usCity("Buckeye", "Arizona"),
  usCity("Lake Havasu City", "Arizona"),
  usCity("Casa Grande", "Arizona"),
  usCity("Maricopa", "Arizona"),
  usCity("Prescott", "Arizona"),
  usCity("Sierra Vista", "Arizona"),
  usCity("Prescott Valley", "Arizona"),
  usCity("Marana", "Arizona"),
  usCity("Bullhead City", "Arizona"),
  usCity("Apache Junction", "Arizona"),
  usCity("Queen Creek", "Arizona"),
  usCity("El Mirage", "Arizona"),
  usCity("San Luis", "Arizona"),
  usCity("Florence", "Arizona"),
  usCity("Douglas", "Arizona"),
  usCity("Sahuarita", "Arizona"),
  usCity("Kingman", "Arizona"),
  usCity("Fountain Hills", "Arizona"),
  usCity("Oro Valley", "Arizona"),
  usCity("Nogales", "Arizona"),
  usCity("Eloy", "Arizona"),
  usCity("Sedona", "Arizona"),
  usCity("Paradise Valley", "Arizona"),
  usCity("Payson", "Arizona"),
  usCity("Globe", "Arizona"),
  usCity("Show Low", "Arizona"),
  usCity("Safford", "Arizona"),
  usCity("Cottonwood", "Arizona"),
  usCity("Camp Verde", "Arizona"),
  usCity("Chino Valley", "Arizona"),
  usCity("Page", "Arizona"),
  usCity("Wickenburg", "Arizona"),
  usCity("Bisbee", "Arizona"),
  usCity("Snowflake", "Arizona"),
  usCity("Winslow", "Arizona"),
  usCity("Holbrook", "Arizona"),
];

export const arkansasCities: City[] = [
  usCity("Little Rock", "Arkansas"),
  usCity("Fort Smith", "Arkansas"),
  usCity("Fayetteville", "Arkansas"),
  usCity("Springdale", "Arkansas"),
  usCity("Jonesboro", "Arkansas"),
  usCity("North Little Rock", "Arkansas"),
  usCity("Conway", "Arkansas"),
  usCity("Rogers", "Arkansas"),
  usCity("Pine Bluff", "Arkansas"),
  usCity("Bentonville", "Arkansas"),
  usCity("Hot Springs", "Arkansas"),
  usCity("Benton", "Arkansas"),
  usCity("Texarkana", "Arkansas"),
  usCity("Sherwood", "Arkansas"),
  usCity("Jacksonville", "Arkansas"),
  usCity("Russellville", "Arkansas"),
  usCity("Bella Vista", "Arkansas"),
  usCity("West Memphis", "Arkansas"),
  usCity("Paragould", "Arkansas"),
  usCity("Cabot", "Arkansas"),
  usCity("Blytheville", "Arkansas"),
  usCity("Siloam Springs", "Arkansas"),
  usCity("Bryant", "Arkansas"),
  usCity("Searcy", "Arkansas"),
  usCity("Van Buren", "Arkansas"),
  usCity("El Dorado", "Arkansas"),
  usCity("Maumelle", "Arkansas"),
  usCity("Harrison", "Arkansas"),
  usCity("Mountain Home", "Arkansas"),
  usCity("Marion", "Arkansas"),
  usCity("Camden", "Arkansas"),
  usCity("Magnolia", "Arkansas"),
  usCity("Arkadelphia", "Arkansas"),
  usCity("Hope", "Arkansas"),
  usCity("Batesville", "Arkansas"),
  usCity("Monticello", "Arkansas"),
  usCity("Stuttgart", "Arkansas"),
  usCity("Malvern", "Arkansas"),
  usCity("Clarksville", "Arkansas"),
  usCity("Centerton", "Arkansas"),
  usCity("Lowell", "Arkansas"),
  usCity("Beebe", "Arkansas"),
  usCity("Osceola", "Arkansas"),
  usCity("Greenwood", "Arkansas"),
  usCity("Wynne", "Arkansas"),
  usCity("Forrest City", "Arkansas"),
  usCity("Newport", "Arkansas"),
  usCity("Heber Springs", "Arkansas"),
  usCity("Morrilton", "Arkansas"),
  usCity("Warren", "Arkansas"),
];

export const californiaCities: City[] = [
  usCity("Los Angeles", "California"),
  usCity("San Diego", "California"),
  usCity("San Jose", "California"),
  usCity("San Francisco", "California"),
  usCity("Fresno", "California"),
  usCity("Sacramento", "California"),
  usCity("Long Beach", "California"),
  usCity("Oakland", "California"),
  usCity("Bakersfield", "California"),
  usCity("Anaheim", "California"),
  usCity("Santa Ana", "California"),
  usCity("Riverside", "California"),
  usCity("Stockton", "California"),
  usCity("Irvine", "California"),
  usCity("Chula Vista", "California"),
  usCity("Fremont", "California"),
  usCity("San Bernardino", "California"),
  usCity("Modesto", "California"),
  usCity("Fontana", "California"),
  usCity("Oxnard", "California"),
  usCity("Moreno Valley", "California"),
  usCity("Huntington Beach", "California"),
  usCity("Glendale", "California"),
  usCity("Santa Clarita", "California"),
  usCity("Garden Grove", "California"),
  usCity("Oceanside", "California"),
  usCity("Rancho Cucamonga", "California"),
  usCity("Santa Rosa", "California"),
  usCity("Ontario", "California"),
  usCity("Lancaster", "California"),
  usCity("Elk Grove", "California"),
  usCity("Palmdale", "California"),
  usCity("Corona", "California"),
  usCity("Salinas", "California"),
  usCity("Pomona", "California"),
  usCity("Torrance", "California"),
  usCity("Hayward", "California"),
  usCity("Escondido", "California"),
  usCity("Sunnyvale", "California"),
  usCity("Pasadena", "California"),
  usCity("Orange", "California"),
  usCity("Fullerton", "California"),
  usCity("Thousand Oaks", "California"),
  usCity("Visalia", "California"),
  usCity("Roseville", "California"),
  usCity("Concord", "California"),
  usCity("Simi Valley", "California"),
  usCity("Santa Clara", "California"),
  usCity("Victorville", "California"),
  usCity("Vallejo", "California"),
  // Additional California cities (sample of top 100)
  usCity("Berkeley", "California"),
  usCity("Fairfield", "California"),
  usCity("Inglewood", "California"),
  usCity("El Monte", "California"),
  usCity("Carlsbad", "California"),
  usCity("Temecula", "California"),
  usCity("Antioch", "California"),
  usCity("Richmond", "California"),
  usCity("Murrieta", "California"),
  usCity("Norwalk", "California"),
  usCity("Daly City", "California"),
  usCity("Burbank", "California"),
  usCity("Santa Maria", "California"),
  usCity("El Cajon", "California"),
  usCity("San Mateo", "California"),
  usCity("Rialto", "California"),
  usCity("Clovis", "California"),
  usCity("Jurupa Valley", "California"),
  usCity("Compton", "California"),
  usCity("Vista", "California"),
  usCity("Mission Viejo", "California"),
  usCity("South Gate", "California"),
  usCity("Vacaville", "California"),
  usCity("Carson", "California"),
  usCity("Hesperia", "California"),
  usCity("Santa Monica", "California"),
  usCity("Westminster", "California"),
  usCity("Redding", "California"),
  usCity("Santa Barbara", "California"),
  usCity("San Leandro", "California"),
  usCity("Chico", "California"),
  usCity("Newport Beach", "California"),
  usCity("San Marcos", "California"),
  usCity("Whittier", "California"),
  usCity("Hawthorne", "California"),
  usCity("Citrus Heights", "California"),
  usCity("Livermore", "California"),
  usCity("Tracy", "California"),
  usCity("Alhambra", "California"),
  usCity("Menifee", "California"),
  usCity("Buena Park", "California"),
  usCity("Hemet", "California"),
  usCity("Lakewood", "California"),
  usCity("Merced", "California"),
  usCity("Indio", "California"),
  usCity("Chino", "California"),
  usCity("Redwood City", "California"),
  usCity("Lake Forest", "California"),
  usCity("Napa", "California"),
  usCity("Tustin", "California"),
];

export const coloradoCities: City[] = [
  usCity("Denver", "Colorado"),
  usCity("Colorado Springs", "Colorado"),
  usCity("Aurora", "Colorado"),
  usCity("Fort Collins", "Colorado"),
  usCity("Lakewood", "Colorado"),
  usCity("Thornton", "Colorado"),
  usCity("Arvada", "Colorado"),
  usCity("Westminster", "Colorado"),
  usCity("Pueblo", "Colorado"),
  usCity("Centennial", "Colorado"),
  usCity("Boulder", "Colorado"),
  usCity("Greeley", "Colorado"),
  usCity("Longmont", "Colorado"),
  usCity("Loveland", "Colorado"),
  usCity("Grand Junction", "Colorado"),
  usCity("Broomfield", "Colorado"),
  usCity("Castle Rock", "Colorado"),
  usCity("Commerce City", "Colorado"),
  usCity("Parker", "Colorado"),
  usCity("Littleton", "Colorado"),
  usCity("Northglenn", "Colorado"),
  usCity("Brighton", "Colorado"),
  usCity("Englewood", "Colorado"),
  usCity("Wheat Ridge", "Colorado"),
  usCity("Fountain", "Colorado"),
  usCity("Lafayette", "Colorado"),
  usCity("Windsor", "Colorado"),
  usCity("Evans", "Colorado"),
  usCity("Golden", "Colorado"),
  usCity("Louisville", "Colorado"),
  usCity("Montrose", "Colorado"),
  usCity("Erie", "Colorado"),
  usCity("Durango", "Colorado"),
  usCity("Cañon City", "Colorado"),
  usCity("Greenwood Village", "Colorado"),
  usCity("Sterling", "Colorado"),
  usCity("Federal Heights", "Colorado"),
  usCity("Fruita", "Colorado"),
  usCity("Steamboat Springs", "Colorado"),
  usCity("Lone Tree", "Colorado"),
  usCity("Firestone", "Colorado"),
  usCity("Frederick", "Colorado"),
  usCity("Castle Pines", "Colorado"),
  usCity("Glenwood Springs", "Colorado"),
  usCity("Alamosa", "Colorado"),
  usCity("Fort Morgan", "Colorado"),
  usCity("Rifle", "Colorado"),
  usCity("Craig", "Colorado"),
  usCity("Delta", "Colorado"),
  usCity("Cortez", "Colorado"),
];

export const connecticutCities: City[] = [
  usCity("Bridgeport", "Connecticut"),
  usCity("New Haven", "Connecticut"),
  usCity("Stamford", "Connecticut"),
  usCity("Hartford", "Connecticut"),
  usCity("Waterbury", "Connecticut"),
  usCity("Norwalk", "Connecticut"),
  usCity("Danbury", "Connecticut"),
  usCity("New Britain", "Connecticut"),
  usCity("Bristol", "Connecticut"),
  usCity("Meriden", "Connecticut"),
  usCity("West Hartford", "Connecticut"),
  usCity("Milford", "Connecticut"),
  usCity("Middletown", "Connecticut"),
  usCity("Norwich", "Connecticut"),
  usCity("Shelton", "Connecticut"),
  usCity("Torrington", "Connecticut"),
  usCity("Trumbull", "Connecticut"),
  usCity("Glastonbury", "Connecticut"),
  usCity("Wallingford", "Connecticut"),
  usCity("Southington", "Connecticut"),
  usCity("Enfield", "Connecticut"),
  usCity("Fairfield", "Connecticut"),
  usCity("Manchester", "Connecticut"),
  usCity("Hamden", "Connecticut"),
  usCity("West Haven", "Connecticut"),
  usCity("Greenwich", "Connecticut"),
  usCity("Stratford", "Connecticut"),
  usCity("East Hartford", "Connecticut"),
  usCity("Groton", "Connecticut"),
  usCity("Farmington", "Connecticut"),
  usCity("Newington", "Connecticut"),
  usCity("Naugatuck", "Connecticut"),
  usCity("Vernon", "Connecticut"),
  usCity("Windsor", "Connecticut"),
  usCity("Wethersfield", "Connecticut"),
  usCity("New London", "Connecticut"),
  usCity("Ansonia", "Connecticut"),
  usCity("New Canaan", "Connecticut"),
  usCity("Windham", "Connecticut"),
  usCity("Simsbury", "Connecticut"),
  usCity("Waterford", "Connecticut"),
  usCity("Ridgefield", "Connecticut"),
  usCity("Westport", "Connecticut"),
  usCity("Darien", "Connecticut"),
  usCity("South Windsor", "Connecticut"),
  usCity("Watertown", "Connecticut"),
  usCity("Guilford", "Connecticut"),
  usCity("Bloomfield", "Connecticut"),
  usCity("Plainville", "Connecticut"),
  usCity("Monroe", "Connecticut"),
];

export const delawareCities: City[] = [
  usCity("Wilmington", "Delaware"),
  usCity("Dover", "Delaware"),
  usCity("Newark", "Delaware"),
  usCity("Middletown", "Delaware"),
  usCity("Smyrna", "Delaware"),
  usCity("Milford", "Delaware"),
  usCity("Seaford", "Delaware"),
  usCity("Georgetown", "Delaware"),
  usCity("Elsmere", "Delaware"),
  usCity("New Castle", "Delaware"),
  usCity("Millsboro", "Delaware"),
  usCity("Laurel", "Delaware"),
  usCity("Harrington", "Delaware"),
  usCity("Camden", "Delaware"),
  usCity("Lewes", "Delaware"),
  usCity("Rehoboth Beach", "Delaware"),
  usCity("Bridgeville", "Delaware"),
  usCity("Selbyville", "Delaware"),
  usCity("Delmar", "Delaware"),
  usCity("Newport", "Delaware"),
  usCity("Blades", "Delaware"),
  usCity("Ocean View", "Delaware"),
  usCity("Milton", "Delaware"),
  usCity("Cheswold", "Delaware"),
  usCity("Wyoming", "Delaware"),
];

export const floridaCities: City[] = [
  usCity("Jacksonville", "Florida"),
  usCity("Miami", "Florida"),
  usCity("Tampa", "Florida"),
  usCity("Orlando", "Florida"),
  usCity("St. Petersburg", "Florida"),
  usCity("Hialeah", "Florida"),
  usCity("Port St. Lucie", "Florida"),
  usCity("Tallahassee", "Florida"),
  usCity("Cape Coral", "Florida"),
  usCity("Fort Lauderdale", "Florida"),
  usCity("Pembroke Pines", "Florida"),
  usCity("Hollywood", "Florida"),
  usCity("Miramar", "Florida"),
  usCity("Gainesville", "Florida"),
  usCity("Coral Springs", "Florida"),
  usCity("Miami Gardens", "Florida"),
  usCity("Clearwater", "Florida"),
  usCity("Palm Bay", "Florida"),
  usCity("Pompano Beach", "Florida"),
  usCity("West Palm Beach", "Florida"),
  usCity("Lakeland", "Florida"),
  usCity("Davie", "Florida"),
  usCity("Miami Beach", "Florida"),
  usCity("Sunrise", "Florida"),
  usCity("Plantation", "Florida"),
  usCity("Boca Raton", "Florida"),
  usCity("Deltona", "Florida"),
  usCity("Palm Coast", "Florida"),
  usCity("Largo", "Florida"),
  usCity("Deerfield Beach", "Florida"),
  usCity("Melbourne", "Florida"),
  usCity("Boynton Beach", "Florida"),
  usCity("Lauderhill", "Florida"),
  usCity("Weston", "Florida"),
  usCity("Fort Myers", "Florida"),
  usCity("Kissimmee", "Florida"),
  usCity("Homestead", "Florida"),
  usCity("Tamarac", "Florida"),
  usCity("Delray Beach", "Florida"),
  usCity("Daytona Beach", "Florida"),
  usCity("North Miami", "Florida"),
  usCity("Wellington", "Florida"),
  usCity("North Port", "Florida"),
  usCity("Jupiter", "Florida"),
  usCity("Ocala", "Florida"),
  usCity("Port Orange", "Florida"),
  usCity("Margate", "Florida"),
  usCity("Coconut Creek", "Florida"),
  usCity("Sanford", "Florida"),
  usCity("Sarasota", "Florida"),
  // Additional top Florida cities
  usCity("Pensacola", "Florida"),
  usCity("Bradenton", "Florida"),
  usCity("Palm Beach Gardens", "Florida"),
  usCity("Pinellas Park", "Florida"),
  usCity("Coral Gables", "Florida"),
  usCity("Doral", "Florida"),
  usCity("Bonita Springs", "Florida"),
  usCity("North Miami Beach", "Florida"),
  usCity("Oakland Park", "Florida"),
  usCity("Fort Pierce", "Florida"),
  usCity("North Lauderdale", "Florida"),
  usCity("Cutler Bay", "Florida"),
  usCity("Altamonte Springs", "Florida"),
  usCity("St. Cloud", "Florida"),
  usCity("Greenacres", "Florida"),
  usCity("Ormond Beach", "Florida"),
  usCity("Hallandale Beach", "Florida"),
  usCity("Winter Garden", "Florida"),
  usCity("Lake Worth", "Florida"),
  usCity("Aventura", "Florida"),
  usCity("Ocoee", "Florida"),
  usCity("Winter Haven", "Florida"),
  usCity("Titusville", "Florida"),
  usCity("Lauderdale Lakes", "Florida"),
  usCity("Rockledge", "Florida"),
];

// Note: For the sake of brevity, this file includes the first several states as samples.
// A full implementation would include all 50 states and their cities.

// Helper function to get all cities from a specific state
export function getCitiesForState(state: string): City[] {
  switch (state) {
    case "Alabama": return alabamaCities;
    case "Alaska": return alaskaCities;
    case "Arizona": return arizonaCities;
    case "Arkansas": return arkansasCities;
    case "California": return californiaCities;
    case "Colorado": return coloradoCities;
    case "Connecticut": return connecticutCities;
    case "Delaware": return delawareCities;
    case "Florida": return floridaCities;
    // Additional states would be added here
    default: return [];
  }
}

// Export a function to get all US cities (as needed)
export function getAllUSCities(): City[] {
  return [
    ...alabamaCities,
    ...alaskaCities,
    ...arizonaCities,
    ...arkansasCities,
    ...californiaCities,
    ...coloradoCities,
    ...connecticutCities,
    ...delawareCities,
    ...floridaCities,
    // Additional states would be included here
  ];
}

// Export major cities for initial display
export const majorUSCities: City[] = [
  usCity("New York", "New York"),
  usCity("Los Angeles", "California"),
  usCity("Chicago", "Illinois"),
  usCity("Houston", "Texas"),
  usCity("Phoenix", "Arizona"),
  usCity("Philadelphia", "Pennsylvania"),
  usCity("San Antonio", "Texas"),
  usCity("San Diego", "California"),
  usCity("Dallas", "Texas"),
  usCity("San Jose", "California"),
  usCity("Austin", "Texas"),
  usCity("Jacksonville", "Florida"),
  usCity("Fort Worth", "Texas"),
  usCity("Columbus", "Ohio"),
  usCity("Charlotte", "North Carolina"),
  usCity("Indianapolis", "Indiana"),
  usCity("San Francisco", "California"),
  usCity("Seattle", "Washington"),
  usCity("Denver", "Colorado"),
  usCity("Washington", "District of Columbia"),
  usCity("Boston", "Massachusetts"),
  usCity("El Paso", "Texas"),
  usCity("Nashville", "Tennessee"),
  usCity("Detroit", "Michigan"),
  usCity("Oklahoma City", "Oklahoma"),
  usCity("Portland", "Oregon"),
  usCity("Las Vegas", "Nevada"),
  usCity("Memphis", "Tennessee"),
  usCity("Louisville", "Kentucky"),
  usCity("Baltimore", "Maryland"),
  usCity("Milwaukee", "Wisconsin"),
  usCity("Albuquerque", "New Mexico"),
  usCity("Tucson", "Arizona"),
  usCity("Fresno", "California"),
  usCity("Sacramento", "California"),
  usCity("Atlanta", "Georgia"),
  usCity("Kansas City", "Missouri"),
  usCity("Colorado Springs", "Colorado"),
  usCity("Omaha", "Nebraska"),
  usCity("Raleigh", "North Carolina"),
  usCity("Miami", "Florida"),
  usCity("Long Beach", "California"),
  usCity("Virginia Beach", "Virginia"),
  usCity("Oakland", "California"),
  usCity("Minneapolis", "Minnesota"),
  usCity("Tampa", "Florida"),
  usCity("Tulsa", "Oklahoma"),
  usCity("Arlington", "Texas"),
  usCity("Wichita", "Kansas"),
  usCity("Bakersfield", "California"),
];

export default {
  getCitiesForState,
  getAllUSCities,
  majorUSCities,
};